package com.classifier
import com.classifier.Animal;

/* Regras gerais que tentam determinar a categoria do animal */

rule "Aquatico"
	no-loop true
	salience 10
	when
		a : Animal(isHabitat("aquatico"))
	then
		a.votePeixes();
		a.voteAnfibios();
		a.voteRepteis();
		a.voteAves();
		a.voteMamiferos();
end

rule "Terrestre"
	no-loop true
	salience 10
	when
		a : Animal(isHabitat("terrestre"))
	then
		a.voteAnfibios();
		a.voteRepteis();
		a.voteAves();
		a.voteMamiferos();
end

rule "Aereo"
	no-loop true
	salience 10
	when
		a : Animal(isHabitat("aereo"))
	then
		a.voteAves();
		a.voteMamiferos();
end

rule "Escamas"
	no-loop true
	salience 10
	when
		a : Animal(isRevestimento("escamas"))
	then
		a.votePeixes();
		a.voteRepteis();
end

rule "Carapaça"
	no-loop true
	salience 10
	when
		a : Animal(isRevestimento("carapaca"))
	then
		a.voteRepteis();
end

rule "Pelos"
	no-loop true
	salience 10
	when
		a : Animal(isRevestimento("pelos"))
	then
		a.voteMamiferos();
end

rule "Pele"
	no-loop true
	salience 10
	when
		a : Animal(isRevestimento("pele"))
	then
		a.voteAnfibios();
		a.voteMamiferos();
end

rule "Cartilagem"
	no-loop true
	salience 10
	when
		a : Animal(isRevestimento("cartilagem"))
	then
		a.votePeixes();
end

rule "Penas"
	no-loop true
	salience 10
	when
		a : Animal(isRevestimento("penas"))
	then
		a.voteAves();
end

rule "Nada"
	no-loop true
	salience 10
	when
		a : Animal(isLocomocao("nada"))
	then
		a.votePeixes();
		a.voteAnfibios();
		a.voteRepteis();
		a.voteAves();
		a.voteMamiferos();
end

rule "Anda"
	no-loop true
	salience 10
	when
		a : Animal(isLocomocao("anda"))
	then
		a.voteAnfibios();
		a.voteRepteis();
		a.voteAves();
		a.voteMamiferos();
end

rule "Rasteja"
	no-loop true
	salience 10
	when
		a : Animal(isLocomocao("rasteja"))
	then
		a.voteAnfibios();
		a.voteRepteis();
		a.voteAves();
end

rule "Voa"
	no-loop true
	salience 10
	when
		a : Animal(isLocomocao("voa"))
	then
		a.voteAves();
		a.voteMamiferos();
end

rule "Oviparo"
	no-loop true
	salience 10
	when
		a : Animal(isReproducao("oviparo"))
	then
		a.voteAnfibios();
		a.voteRepteis();
		a.voteAves();
end

rule "Ovuliparo"
	no-loop true
	salience 10
	when
		a : Animal(isReproducao("ovuliparo"))
	then
		a.votePeixes();
		a.voteAnfibios();
end

rule "Viviparo"
	no-loop true
	salience 10
	when
		a : Animal(isReproducao("viviparo"))
	then
		a.voteMamiferos();
end

rule "Carnivoro"
	no-loop true
	salience 10
	when
		a : Animal(isAlimentacao("carnivoro"))
	then
		a.votePeixes();
		a.voteAnfibios();
		a.voteRepteis();
		a.voteAves();
		a.voteMamiferos();
end

rule "Herbivoro"
	no-loop true
	salience 10
	when
		a : Animal(isAlimentacao("herbivoro"))
	then
		a.votePeixes();
		a.voteRepteis();
		a.voteAves();
		a.voteMamiferos();
end

rule "Branquial"
	no-loop true
	salience 10
	when
		a : Animal(isRespiracao("branquial"))
	then
		a.votePeixes();
end

rule "Cutanea"
	no-loop true
	salience 10
	when
		a : Animal(isRespiracao("cutanea"))
	then
		a.voteAnfibios();
end

rule "Pulmonar"
	no-loop true
	salience 10
	when
		a : Animal(isRespiracao("pulmonar"))
	then
		a.voteAnfibios();
		a.voteRepteis();
		a.voteAves();
		a.voteMamiferos();
end

/* Regras que descartam categorias que não são possíveis */

rule "Exclui_Terrestre"
	no-loop true
	salience 5
	when
		a : Animal(isHabitat("terrestre"))
	then
		a.zeroPeixes();
end

rule "Exclui_Aereo"
	no-loop true
	salience 5
	when
		a : Animal(isHabitat("aereo"))
	then
		a.zeroPeixes();
		a.zeroAnfibios();
		a.zeroRepteis();
end

rule "Exclui_Escamas"
	no-loop true
	salience 5
	when
		a : Animal(isRevestimento("escamas"))
	then
		a.zeroAnfibios();
		a.zeroAves();
		a.zeroMamiferos();
end

rule "Exclui_Carapaça"
	no-loop true
	salience 5
	when
		a : Animal(isRevestimento("carapaca"))
	then
		a.zeroPeixes();
		a.zeroAnfibios();
		a.zeroAves();
		a.zeroMamiferos();
end

rule "Exclui_Pelos"
	no-loop true
	salience 5
	when
		a : Animal(isRevestimento("pelos"))
	then
		a.zeroPeixes();
		a.zeroAnfibios();
		a.zeroRepteis();
		a.zeroAves();
end

rule "Exclui_Pele"
	no-loop true
	salience 5
	when
		a : Animal(isRevestimento("pele"))
	then
		a.zeroPeixes();
		a.zeroRepteis();
		a.zeroAves();
end

rule "Exclui_Cartilagem"
	no-loop true
	salience 5
	when
		a : Animal(isRevestimento("cartilagem"))
	then
		a.zeroAnfibios();
		a.zeroRepteis();
		a.zeroAves();
		a.zeroMamiferos();
end

rule "Exclui_Penas"
	no-loop true
	salience 5
	when
		a : Animal(isRevestimento("penas"))
	then
		a.zeroPeixes();
		a.zeroAnfibios();
		a.zeroRepteis();
		a.zeroMamiferos();
end

rule "Exclui_Anda"
	no-loop true
	salience 5
	when
		a : Animal(isLocomocao("anda"))
	then
		a.zeroPeixes();
end

rule "Exclui_Rasteja"
	no-loop true
	salience 5
	when
		a : Animal(isLocomocao("rasteja"))
	then
		a.zeroPeixes();
		a.zeroMamiferos();
end

rule "Exclui_Voa"
	no-loop true
	salience 5
	when
		a : Animal(isLocomocao("voa"))
	then
		a.zeroPeixes();
		a.zeroAnfibios();
		a.zeroRepteis();
end

rule "Exclui_Oviparo"
	no-loop true
	salience 5
	when
		a : Animal(isReproducao("oviparo"))
	then
		a.zeroPeixes();
		a.zeroMamiferos();
end

rule "Exclui_Ovuliparo"
	no-loop true
	salience 5
	when
		a : Animal(isReproducao("ovuliparo"))
	then
		a.zeroAves();
		a.zeroMamiferos();
		a.zeroRepteis();
end

rule "Exclui_Viviparo"
	no-loop true
	salience 5
	when
		a : Animal(isReproducao("viviparo"))
	then
		a.zeroPeixes();
		a.zeroAnfibios();
		a.zeroRepteis();
		a.zeroAves();
end

rule "Exclui_Herbivoro"
	no-loop true
	salience 5
	when
		a : Animal(isAlimentacao("herbivoro"))
	then
		a.zeroAnfibios();
end

rule "Exclui_Branquial"
	no-loop true
	salience 5
	when
		a : Animal(isRespiracao("branquial"))
	then
		a.zeroAnfibios();
		a.zeroRepteis();
		a.zeroAves();
		a.zeroMamiferos();
end

rule "Exclui_Cutanea"
	no-loop true
	salience 5
	when
		a : Animal(isRespiracao("cutanea"))
	then
		a.zeroPeixes();
		a.zeroRepteis();
		a.zeroAves();
		a.zeroMamiferos();
end

rule "Exclui_Pulmonar"
	no-loop true
	salience 5
	when
		a : Animal(isRespiracao("pulmonar"))
	then
		a.zeroPeixes();
end

/* Regras que determinam animais específicos */

rule "Tubarão"
	no-loop true
	salience 1
	when
		a : Animal(isHabitat("aquatico"), !isHabitat("terrestre"), !isHabitat("aereo"),
		isRevestimento("cartilagem"), !isRevestimento("pele"), !isRevestimento("escamas"), !isRevestimento("pelos"),
		!isRevestimento("penas"), !isRevestimento("carapaca"),
		isLocomocao("nada"), !isLocomocao("voa"), !isLocomocao("rasteja"), !isLocomocao("anda"),
		isReproducao("ovuliparo"), !isReproducao("oviparo"), !isReproducao("viviparo"),
		isAlimentacao("carnivoro"), !isAlimentacao("herbivoro"), isRespiracao("branquial"),
		!isRespiracao("cutanea"), !isRespiracao("pulmonar"))
	then
		a.setNome("Tubarão");
end

/*rule "Tubarão"
	no-loop true
	salience 1
	when
		a : Animal(isHabitat("aquatico"), !isHabitat("terrestre"), !isHabitat("aereo"),
		isRevestimento("cartilagem"), !isRevestimento("pele"), !isRevestimento("escamas"), !isRevestimento("pelos"),
		!isRevestimento("penas"), !isRevestimento("carapaca"),
		isLocomocao("nada"), !isLocomocao("voa"), !isLocomocao("rasteja"), !isLocomocao("anda"),
		isReproducao("ovuliparo"), !isReproducao("oviparo"), !isReproducao("viviparo"),
		isAlimentacao("carnivoro"), !isAlimentacao("herbivoro"), isRespiracao("branquial"),
		!isRespiracao("cutanea"), !isRespiracao("pulmonar"))
	then
		a.setNome("Tubarão");
end*/

rule "Sapo"
	no-loop true
	salience 1
	when
		a : Animal(isHabitat("aquatico"), isHabitat("terrestre"), !isHabitat("aereo"), isRevestimento("pele"),
		!isRevestimento("cartilagem"), !isRevestimento("escamas"), !isRevestimento("pelos"), !isRevestimento("penas"), !isRevestimento("carapaca"),
		isLocomocao("nada"), isLocomocao("anda"), isLocomocao("rasteja"), !isLocomocao("voa"), isReproducao("ovuliparo"), !isReproducao("oviparo"),
		!isReproducao("viviparo"), isAlimentacao("carnivoro"), !isAlimentacao("herbivoro"), isRespiracao("cutanea"), isRespiracao("pulmonar"),
		!isRespiracao("branquial"))
	then
		a.setNome("Sapo");
end


rule "Salamandra"
	no-loop true
	salience 1
	when
		a : Animal(isHabitat("aquatico"), isHabitat("terrestre"), !isHabitat("aereo"), isRevestimento("pele"),
		!isRevestimento("cartilagem"), !isRevestimento("escamas"), !isRevestimento("pelos"), !isRevestimento("penas"), !isRevestimento("carapaca"),
		isLocomocao("nada"), isLocomocao("anda"), isLocomocao("rasteja"), !isLocomocao("voa"), !isReproducao("ovuliparo"), isReproducao("oviparo"),
		!isReproducao("viviparo"), isAlimentacao("carnivoro"), !isAlimentacao("herbivoro"), isRespiracao("cutanea"), isRespiracao("pulmonar"),
		!isRespiracao("branquial"))
	then
		a.setNome("Salamandra");
end

rule "Jacaré"
	no-loop true
	salience 1
	when
		a : Animal(isHabitat("aquatico"), isHabitat("terrestre"), !isHabitat("aereo"), isRevestimento("escamas"), !isRevestimento("pele"),
		!isRevestimento("cartilagem"), !isRevestimento("pelos"), !isRevestimento("penas"), !isRevestimento("carapaca"), isLocomocao("nada"), 
		isLocomocao("anda"), !isLocomocao("rasteja"), !isLocomocao("voa"), !isReproducao("ovuliparo"), isReproducao("oviparo"),
		!isReproducao("viviparo"), isAlimentacao("carnivoro"), !isAlimentacao("herbivoro"), isRespiracao("pulmonar"), !isRespiracao("cutanea"),
		!isRespiracao("branquial"))
	then
		a.setNome("Jacaré");
end

rule "Cobra"
	no-loop true
	salience 1
	when
		a : Animal(isHabitat("aquatico"), isHabitat("terrestre"), !isHabitat("aereo"), isRevestimento("escamas"), !isRevestimento("pele"),
		!isRevestimento("cartilagem"), !isRevestimento("pelos"), !isRevestimento("penas"), !isRevestimento("carapaca"), isLocomocao("nada"), 
		isLocomocao("rasteja"), !isLocomocao("anda"), !isLocomocao("voa"), isReproducao("oviparo"), !isReproducao("ovuliparo"), !isReproducao("viviparo"),
		isAlimentacao("carnivoro"), !isAlimentacao("herbivoro"), isRespiracao("pulmonar"), !isRespiracao("cutanea"), !isRespiracao("branquial"))
	then
		a.setNome("Cobra");
end

rule "Tartaruga"
	no-loop true
	salience 1
	when
		a : Animal(isHabitat("aquatico"), isHabitat("terrestre"), !isHabitat("aereo"), isRevestimento("escamas"), !isRevestimento("pele"),
		!isRevestimento("cartilagem"), !isRevestimento("pelos"), !isRevestimento("penas"), isRevestimento("carapaca"), isLocomocao("nada"), 
		!isLocomocao("rasteja"), isLocomocao("anda"), !isLocomocao("voa"), isReproducao("oviparo"), !isReproducao("ovuliparo"), !isReproducao("viviparo"),
		!isAlimentacao("carnivoro"), isAlimentacao("herbivoro"), isRespiracao("pulmonar"), !isRespiracao("cutanea"), !isRespiracao("branquial"))
	then
		a.setNome("Tartaruga");
end

rule "Pinguim"
	no-loop true
	salience 1
	when
		a : Animal(isHabitat("aquatico"), isHabitat("terrestre"), !isHabitat("aereo"), !isRevestimento("escamas"), !isRevestimento("pele"),
		!isRevestimento("cartilagem"), !isRevestimento("pelos"), isRevestimento("penas"), !isRevestimento("carapaca"), isLocomocao("nada"),
		isLocomocao("anda"), !isLocomocao("voa"), !isLocomocao("rasteja"), isReproducao("oviparo"), !isReproducao("viviparo"), !isReproducao("ovuliparo"),
		isAlimentacao("carnivoro"), !isAlimentacao("herbivoro"), isRespiracao("pulmonar"), !isRespiracao("cutanea"), !isRespiracao("branquial"))
	then
		a.setNome("Pinguim");
end

rule "Pato"
	no-loop true
	salience 1
	when
		a : Animal(isHabitat("aquatico"), isHabitat("terrestre"), isHabitat("aereo"), !isRevestimento("escamas"), !isRevestimento("pele"),
		!isRevestimento("cartilagem"), !isRevestimento("pelos"), isRevestimento("penas"), !isRevestimento("carapaca"), isLocomocao("nada"),
		isLocomocao("anda"), isLocomocao("voa"), !isLocomocao("rasteja"), isReproducao("oviparo"), !isReproducao("viviparo"), !isReproducao("ovuliparo"),
		!isAlimentacao("carnivoro"), isAlimentacao("herbivoro"), isRespiracao("pulmonar"), !isRespiracao("cutanea"), !isRespiracao("branquial"))
	then
		a.setNome("Pato");
end

rule "Galinha"
	no-loop true
	salience 1
	when
		a : Animal(!isHabitat("aquatico"), isHabitat("terrestre"), !isHabitat("aereo"), !isRevestimento("escamas"), !isRevestimento("pele"),
		!isRevestimento("cartilagem"), !isRevestimento("pelos"), isRevestimento("penas"), !isRevestimento("carapaca"), !isLocomocao("nada"),
		isLocomocao("anda"), isLocomocao("voa"), !isLocomocao("rasteja"), isReproducao("oviparo"), !isReproducao("viviparo"), !isReproducao("ovuliparo"),
		!isAlimentacao("carnivoro"), isAlimentacao("herbivoro"), isRespiracao("pulmonar"), !isRespiracao("cutanea"), !isRespiracao("branquial"))
	then
		a.setNome("Galinha");
end

rule "Macaco"
	no-loop true
	salience 1
	when
		a : Animal(!isHabitat("aquatico"), isHabitat("terrestre"), !isHabitat("aereo"), !isRevestimento("escamas"), !isRevestimento("pele"),
		!isRevestimento("cartilagem"), isRevestimento("pelos"), !isRevestimento("penas"), !isRevestimento("carapaca"), !isLocomocao("nada"),
		isLocomocao("anda"), !isLocomocao("voa"), !isLocomocao("rasteja"), !isReproducao("oviparo"), isReproducao("viviparo"), !isReproducao("ovuliparo"),
		isAlimentacao("carnivoro"), isAlimentacao("herbivoro"), isRespiracao("pulmonar"), !isRespiracao("cutanea"), !isRespiracao("branquial"))
	then
		a.setNome("Macaco");
end

rule "Baleia"
	no-loop true
	salience 1
	when
		a : Animal(isHabitat("aquatico"), !isHabitat("terrestre"), !isHabitat("aereo"), !isRevestimento("escamas"), isRevestimento("pele"),
		!isRevestimento("cartilagem"), !isRevestimento("pelos"), !isRevestimento("penas"), !isRevestimento("carapaca"), isLocomocao("nada"),
		!isLocomocao("anda"), !isLocomocao("voa"), !isLocomocao("rasteja"), !isReproducao("oviparo"), isReproducao("viviparo"), !isReproducao("ovuliparo"),
		isAlimentacao("carnivoro"), isAlimentacao("herbivoro"), isRespiracao("pulmonar"), !isRespiracao("cutanea"), !isRespiracao("branquial"))
	then
		a.setNome("Baleia");
end

rule "Morcego"
	no-loop true
	salience 1
	when
		a : Animal(!isHabitat("aquatico"), !isHabitat("terrestre"), isHabitat("aereo"), !isRevestimento("escamas"), !isRevestimento("pele"),
		!isRevestimento("cartilagem"), isRevestimento("pelos"), !isRevestimento("penas"), !isRevestimento("carapaca"), !isLocomocao("nada"),
		!isLocomocao("anda"), isLocomocao("voa"), !isLocomocao("rasteja"), !isReproducao("oviparo"), isReproducao("viviparo"), !isReproducao("ovuliparo"),
		isAlimentacao("carnivoro"), isAlimentacao("herbivoro"), isRespiracao("pulmonar"), !isRespiracao("cutanea"), !isRespiracao("branquial"))
	then
		a.setNome("Morcego");
end
